name: Module Validation
on:
  pull_request:
    branches: [ main ]
permissions:
  contents: read
jobs:
  lint:
    # Use the shared static analysis workflow
    uses: rhyscraig/aws-terraform-platform-aws-workflows/.github/workflows/reusable-static-analysis.yaml@v2.0.0
    with:
      working-directory: "."
      tflint-version: "latest"
