name: Module Validation
on:
  pull_request:
    branches: [ main ]
permissions:
  contents: read
jobs:
  lint:
    # Use the shared static analysis workflow
    uses: BT-IT-Infrastructure-CloudOps/aws-workflows/.github/workflows/reusable-static-analysis.yaml@v0.0.2
    with:
      working-directory: "."
      tflint-version: "latest"
