name: Release
on:
  push:
    branches: [ main ]
    paths:
      - 'modules/**'
      - '.github/release.yml'
permissions:
  contents: write
jobs:
  release:
    uses: BT-IT-Infrastructure-CloudOps/aws-workflows/.github/workflows/reusable-tagging.yaml@v0.0.2
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
