name: "Module Release"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'modules/**'

jobs:
  # 🛡️ Security
  scan:
    uses: rhyscraig/aws-terraform-platform-aws-workflows/.github/workflows/reusable-secret-scan.yaml@v2.0.0

  # 🧪 Test (Using tfctl to validate modules)
  validate:
    needs: [scan]
    uses: rhyscraig/aws-terraform-platform-aws-workflows/.github/workflows/reusable-static-analysis.yaml@v2.0.0
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  # 📦 Release
  release:
    needs: [validate]
    uses: rhyscraig/aws-terraform-platform-aws-workflows/.github/workflows/reusable-tagging.yaml@v2.0.0
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
